# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-yaml
      - id: fix-byte-order-marker
  # - repo: https://github.com/PyCQA/isort
  #  rev: 5.12.0
  #  hooks:
  #    - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.275'
    hooks:
      - id: ruff
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.5'
    hooks:
      - id: bandit
        args: ["-c", "./pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: YAML Lint
        args: [-c, ./yamllint-config.yaml]
